### ISSUE TITLE
WP-API endpoints 404 on App Engine

### ISSUE THREAD

**Issue by mattrepublic** [WP-API/WP-API#1888]
On a fresh Google App Engine instance, WP-API endpoints are returning a 404 for everything except the initial "/" endpoint. I've tested in Paw and the Rest API Console plugin.

<img width="1060" alt="screen shot 2015-12-21 at 8 54 09 pm" src="https://cloud.githubusercontent.com/assets/645847/11946113/36343bc8-a825-11e5-9b68-9a8cc96832c3.png">

Permalink settings:  Post name
WP-API version:  Version 2.0-beta9
WP version:  4.4
Instance url:  https://alohomora.brewbird.io

This same setup works fine on WPEngine.

**Comment by mattrepublic** [comment]
G.A.E. uses handlers as defined in `app.yaml`. This is their WordPress default config...

```
handlers:
- url: /(.*\.(htm|html|css|js))$
  static_files: public.built/\1
  upload: public.built/.*\.(htm|html|css|js)$
  application_readable: true

- url: /wp-content/(.*\.(ico|jpg|jpeg|png|gif|woff|ttf|otf|eot|svg))$
  static_files: public.built/wp-content/\1
  upload: public.built/wp-content/.*\.(ico|jpg|jpeg|png|gif|woff|ttf|otf|eot|svg)$
  application_readable: true

- url: /(.*\.(ico|jpg|jpeg|png|gif|woff|ttf|otf|eot|svg))$
  static_files: public.built/\1
  upload: public.built/.*\.(ico|jpg|jpeg|png|gif|woff|ttf|otf|eot|svg)$
  application_readable: true

- url: /wp-includes/images/media/(.*\.(ico|jpg|jpeg|png|gif|woff|ttf|otf|eot|svg))$
  static_files: public.built/wp-includes/images/media/\1
  upload: public.built/wp-includes/images/media/.*\.(ico|jpg|jpeg|png|gif|woff|ttf|otf|eot|svg)$
  application_readable: true

- url: /wp-admin/(.+)
  script: public.built/wp-admin/\1
  secure: always

- url: /wp-admin/
  script: public.built/wp-admin/index.php
  secure: always

- url: /wp-login.php
  script: public.built/wp-login.php
  secure: always

- url: /wp-cron.php
  script: public.built/wp-cron.php
  login: admin

- url: /xmlrpc.php
  script: public.built/xmlrpc.php

- url: /wp-(.+).php
  script: public.built/wp-\1.php

- url: /(.+)?/?
  script: public.built/index.php
```
